ConsoleUtilities: src/ConsoleTable.c File Reference
src/ConsoleTable.c File Reference
/console-utilities/src/ConsoleTable.c
#include "ConsoleTable.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "StringUtilities.h"
Functions
ConsoleTableT * ConsoleTableCreate ()
int ConsoleTableAddField (ConsoleTableT *tableObj, unsigned width, const char *name, enum ConsoleTableAlignment alignment)
void ConsoleTableSetLinePrepend (ConsoleTableT *tableObj, const char *prependstr)
void ConsoleTableSetLineAppend (ConsoleTableT *tableObj, const char *appendStr)
void ConsoleTableSetColDelimiter (ConsoleTableT *tableObj, const char *colDelimiterStr)
void ConsoleTableSetPadding (ConsoleTableT *tableObj, unsigned padding)
static void ConsoleTableFillCellHelper (ConsoleTableT *tableObj, const char *content, unsigned i)
void ConsoleTableFillCell (ConsoleTableT *tableObj, const char *content)
void ConsoleTablePrintHeader (ConsoleTableT *tableObj)
void ConsoleTableDelete (ConsoleTableT *tableObj)
Detailed Description
/console-utilities/src/ConsoleTable.c
Date:
22/03/2010
Author:
Matheus Neder <matheusneder@gmail.com>
Definition in file ConsoleTable.c.
Function Documentation
int ConsoleTableAddField (ConsoleTableT * tableObj, unsigned width, const char * name, enum ConsoleTableAlignment alignment)
Definition at line 48 of file ConsoleTable.c.
References ConsoleTable::Field::alignment, CONSOLE_TABLE_FIELD_NAME_MAXLEN, ConsoleTable::fields, ConsoleTable::Field::name, ConsoleTable::numFields, and ConsoleTable::Field::width.
ConsoleTableT* ConsoleTableCreate ()
Definition at line 32 of file ConsoleTable.c.
References ConsoleTable::colDelimiter, CONSOLE_TABLE_DEFAULT_COL_DELIMITER, ConsoleTable::fields, ConsoleTable::lineAppend, ConsoleTable::linePrepend, ConsoleTable::numFields, and ConsoleTable::padding.
void ConsoleTableDelete (ConsoleTableT * tableObj)
Definition at line 172 of file ConsoleTable.c.
References ConsoleTable::fields.
void ConsoleTableFillCell (ConsoleTableT * tableObj, const char * content)
Definition at line 140 of file ConsoleTable.c.
References ConsoleTableFillCellHelper(), ConsoleTable::lineAppend, ConsoleTable::linePrepend, and ConsoleTable::numFields.
static void ConsoleTableFillCellHelper (ConsoleTableT * tableObj, const char * content, unsigned i) [static]
Definition at line 115 of file ConsoleTable.c.
References ConsoleTable::Field::alignment, ConsoleTable::colDelimiter, CONSOLE_TABLE_ALIGNMENT_LEFT, ConsoleTable::fields, ConsoleTable::padding, and ConsoleTable::Field::width.
Referenced by ConsoleTableFillCell(), and ConsoleTablePrintHeader().
void ConsoleTablePrintHeader (ConsoleTableT * tableObj)
Definition at line 161 of file ConsoleTable.c.
References ConsoleTableFillCellHelper(), ConsoleTable::fields, ConsoleTable::lineAppend, ConsoleTable::linePrepend, ConsoleTable::Field::name, and ConsoleTable::numFields.
void ConsoleTableSetColDelimiter (ConsoleTableT * tableObj, const char * colDelimiterStr)
Definition at line 82 of file ConsoleTable.c.
References ConsoleTable::colDelimiter, and CONSOLE_TABLE_MAX_SEPARATOR_LEN.
void ConsoleTableSetLineAppend (ConsoleTableT * tableObj, const char * appendStr)
Definition at line 76 of file ConsoleTable.c.
References CONSOLE_TABLE_MAX_SEPARATOR_LEN, and ConsoleTable::lineAppend.
void ConsoleTableSetLinePrepend (ConsoleTableT * tableObj, const char * prependstr)
Definition at line 70 of file ConsoleTable.c.
References CONSOLE_TABLE_MAX_SEPARATOR_LEN, and ConsoleTable::linePrepend.
void ConsoleTableSetPadding (ConsoleTableT * tableObj, unsigned padding)
Definition at line 88 of file ConsoleTable.c.
References ConsoleTable::padding.