RootFinding: Parte Generica
Parte Generica
Data Structures
struct RootFindingBase
Estrutura de dados para RootFindingBase.
Typedefs
typedef struct RootFindingBase RootFindingBaseT
Apelido para struct RootFindingBase.
Functions
RootFindingBaseT * RootFindingBaseCreate (muParserHandle_t mupObj, RootFindingDoubleT *varPtr)
Cria o objeto RootFindingBase.
void RootFindingBaseDelete (RootFindingBaseT *obj)
Apaga o objeto RootFindingBase.
RootFindingBoolT RootFindingBaseSetRange (RootFindingBaseT *rootsObj, RootFindingDoubleT a, RootFindingDoubleT b)
Define o intervalo para procura da raiz.
RootFindingDoubleT RootFindingBaseEval (RootFindingBaseT *rootsObj, RootFindingDoubleT value)
Avalia a funcao em um ponto.
RootFindingDoubleT RootFindingBase2nDiffEval (RootFindingBaseT *rootsObj, RootFindingDoubleT value)
Avalia a 2a. diferencial da funcao em um ponto.
RootFindingDoubleT RootFindingBaseDiffEval (RootFindingBaseT *rootsObj, RootFindingDoubleT value)
Avalia a diferencial da funcao em um ponto.
void RootFindingBaseReset (RootFindingBaseT *rootsObj)
Reinicializa o objeto struct RootFindingBase.
int RootFindingBaseGetErrorCode (RootFindingBaseT *rootsObj)
Obtem o codigo de erro.
int RootFindingBaseGetStateCode (RootFindingBaseT *rootsObj)
Obtem o codigo referente ao estado do objeto.
const char * RootFindingBaseGetErrorMessage (RootFindingBaseT *rootsObj)
Obtem a mensagem de erro.
const char * RootFindingBaseGetStateMessage (RootFindingBaseT *rootsObj)
Obtem a mensagem referente ao estado do objeto.
RootFindingBoolT RootFindingBaseHasError (RootFindingBaseT *rootsObj)
Verifica se ha erros.
static RootFindingBoolT isRangeError (RootFindingBaseT *rootsObj)
Verify if errorCode is a RangeError.
Typedef Documentation
typedef struct RootFindingBase RootFindingBaseT
Apelido para struct RootFindingBase.
Definition at line 83 of file RootFindingBase.h.
Function Documentation
static RootFindingBoolT isRangeError (RootFindingBaseT * rootsObj) [static, private]
Verify if errorCode is a RangeError.
Definition at line 71 of file RootFindingBase.c.
References RootFindingBase::errorCode.
Referenced by RootFindingBaseSetRange().
RootFindingDoubleT RootFindingBase2nDiffEval (RootFindingBaseT * rootsObj, RootFindingDoubleT value)
Avalia a 2a. diferencial da funcao em um ponto.
Parameters:
rootsObj Ponteiro para o objeto struct RootFindingBase
value Valor do ponto a ser avaliado
Returns:
Avaliacao da 2a. dif da funcao no ponto
Definition at line 117 of file RootFindingBase.c.
References Mup2ndDiff(), RootFindingBase::mupObj, and RootFindingBase::varPtr.
Referenced by RootFindingCordasInit(), and RootFindingNewtonRhapsonInit().
RootFindingBaseT* RootFindingBaseCreate (muParserHandle_t mupObj, RootFindingDoubleT * varPtr)
Cria o objeto RootFindingBase.
Parameters:
mupObj Ponteiro para o objeto muParser contendo a expressao
varPtr Pontero para a variavel relacionada a expressao no objeto muParser referente a qual eixo deve se procurar a raiz
Returns:
Ponteiro para o objeto criado
Definition at line 32 of file RootFindingBase.c.
References RootFindingBase::mupObj, RootFindingBaseReset(), RootFindingPegaso::rootsObj, and RootFindingBase::varPtr.
void RootFindingBaseDelete (RootFindingBaseT * obj)
Apaga o objeto RootFindingBase.
Parameters:
obj Ponteiro para o objeto RootFindingBase
Definition at line 61 of file RootFindingBase.c.
RootFindingDoubleT RootFindingBaseDiffEval (RootFindingBaseT * rootsObj, RootFindingDoubleT value)
Avalia a diferencial da funcao em um ponto.
Parameters:
rootsObj Ponteiro para o objeto struct RootFindingBase
value Valor do ponto a ser avaliado
Returns:
Avaliacao da dif da funcao no ponto
Definition at line 124 of file RootFindingBase.c.
References MupDiff(), RootFindingBase::mupObj, and RootFindingBase::varPtr.
Referenced by getNextX().
RootFindingDoubleT RootFindingBaseEval (RootFindingBaseT * rootsObj, RootFindingDoubleT value)
Avalia a funcao em um ponto.
Parameters:
rootsObj Ponteiro para o objeto struct RootFindingBase
value Valor do ponto a ser avaliado
Returns:
Avaliacao da funcao no ponto
Definition at line 110 of file RootFindingBase.c.
References RootFindingBase::mupObj, and RootFindingBase::varPtr.
Referenced by RootFindingBaseReset(), RootFindingBaseSetRange(), RootFindingBissecaoFindNewRange(), RootFindingBissecaoInit(), RootFindingBissecaoPerformIteration(), RootFindingCordasInit(), RootFindingCordasPerformIteration(), RootFindingNewtonRhapsonInit(), RootFindingNewtonRhapsonPerformIteration(), RootFindingPegasoInit(), and RootFindingPegasoPerformIteration().
int RootFindingBaseGetErrorCode (RootFindingBaseT * rootsObj)
Obtem o codigo de erro.
Definition at line 131 of file RootFindingBase.c.
References RootFindingBase::errorCode.
const char* RootFindingBaseGetErrorMessage (RootFindingBaseT * rootsObj)
Obtem a mensagem de erro.
Definition at line 143 of file RootFindingBase.c.
References RootFindingBase::a, RootFindingBase::b, RootFindingBase::errorCode, msg, MSG_ROOTS_MUP_EVAL_ERROR, MSG_ROOTS_NO_ERROR, MSG_ROOTS_RANGE_ERROR_FA_OR_FB_ISINFINITY, MSG_ROOTS_RANGE_ERROR_PROD_FA_FB_NOT_LT_0, and MSG_ROOTS_UNKNOW_ERROR.
int RootFindingBaseGetStateCode (RootFindingBaseT * rootsObj)
Obtem o codigo referente ao estado do objeto.
Definition at line 136 of file RootFindingBase.c.
References RootFindingBase::state.
const char* RootFindingBaseGetStateMessage (RootFindingBaseT * rootsObj)
Obtem a mensagem referente ao estado do objeto.
Definition at line 164 of file RootFindingBase.c.
References msg, MSG_ROOTS_EXACT_ROOT_FOUND, MSG_ROOTS_RANGE_NOT_SET, MSG_ROOTS_READY, MSG_ROOTS_UNKNOW_STATE, RootFindingBase::state, and RootFindingBase::x.
RootFindingBoolT RootFindingBaseHasError (RootFindingBaseT * rootsObj)
Verifica se ha erros.
Returns:
TRUE caso haja erro
Definition at line 180 of file RootFindingBase.c.
References RootFindingBase::errorCode.
Referenced by RootFindingBaseSetRange().
void RootFindingBaseReset (RootFindingBaseT * rootsObj)
Reinicializa o objeto struct RootFindingBase.
Parameters:
rootsObj Ponteiro para o objeto struct RootFindingBase
Definition at line 47 of file RootFindingBase.c.
References RootFindingBase::e, RootFindingBase::errorCode, infinity(), RootFindingBase::mupObj, RootFindingBaseEval(), and RootFindingBase::state.
Referenced by RootFindingBaseCreate().
RootFindingBoolT RootFindingBaseSetRange (RootFindingBaseT * rootsObj, RootFindingDoubleT a, RootFindingDoubleT b)
Define o intervalo para procura da raiz.
Parameters:
rootsObj Ponteiro para o objeto RootFindingBase
a
b
Returns:
TRUE em caso de sucesso, quando f(a) * f(b) < 0 'e' f(a), f(b) sejam ambos diferentes de infinito
Definition at line 77 of file RootFindingBase.c.
References RootFindingBase::a, RootFindingBase::b, RootFindingBase::errorCode, FALSE, isRangeError(), RootFindingBaseEval(), RootFindingBaseHasError(), RootFindingBase::state, and TRUE.