RootFinding: Metodo de Pegaso
Metodo de Pegaso
Data Structures
struct RootFindingPegaso
Estrutura de dados para o Metodo de Pegaso.
Defines
#define PEGASO_DEFAULT_MAX_ITERATIONS 100
#define PEGASO_DEFAULT_TOLERANCE 1e-7
Typedefs
typedef struct RootFindingPegaso RootFindingPegasoT
Apelido para struct RootFindingPegaso.
Functions
RootFindingPegasoT * RootFindingPegasoCreate (RootFindingBaseT *rootsObj)
Cria um objeto do tipo struct RootFindingPegaso.
RootFindingBoolT RootFindingPegasoInit (RootFindingPegasoT *pegasoObj)
Inicializa o objeto RootFindingPegaso.
void RootFindingPegasoDelete (RootFindingPegasoT *obj)
Apaga a instancia do objeto RootFindingPegaso.
RootFindingBoolT RootFindingPegasoPerformIteration (RootFindingPegasoT *pegasoObj)
Realiza a iteracao.
int RootFindingPegasoGetErrorCode (RootFindingPegasoT *pegasoObj)
Obtem o codigo de erro.
int RootFindingPegasoGetStateCode (RootFindingPegasoT *pegasoObj)
Obtem o codigo referente ao estado do objeto.
const char * RootFindingPegasoGetErrorMessage (RootFindingPegasoT *pegasoObj)
Obtem a mensagem de erro.
const char * RootFindingPegasoGetStateMessage (RootFindingPegasoT *pegasoObj)
Obtem a mensagem referente ao estado do objeto.
RootFindingBoolT RootFindingPegasoHasError (RootFindingPegasoT *pegasoObj)
Verifica se ha erros.
static void setError (RootFindingPegasoT *pegasoObj, int errorCode)
Set error code and change state to PEGASO_ERROR_FOUND.
static void resetError (RootFindingPegasoT *pegasoObj)
static RootFindingDoubleT getNextX (RootFindingPegasoT *pegasoObj)
Obtem o valor para o proximo x.
Define Documentation
#define PEGASO_DEFAULT_MAX_ITERATIONS 100
Definition at line 38 of file RootFindingPegaso.h.
Referenced by RootFindingPegasoCreate().
#define PEGASO_DEFAULT_TOLERANCE 1e-7
Definition at line 39 of file RootFindingPegaso.h.
Referenced by RootFindingPegasoCreate().
Typedef Documentation
typedef struct RootFindingPegaso RootFindingPegasoT
Apelido para struct RootFindingPegaso.
Definition at line 84 of file RootFindingPegaso.h.
Function Documentation
static RootFindingDoubleT getNextX (RootFindingPegasoT * pegasoObj) [static, private]
Obtem o valor para o proximo x.
Parameters:
pegasoObj Ponteiro para objeto struct RootFindingPegaso
Returns:
Valor do proximo x
Definition at line 93 of file RootFindingPegaso.c.
References RootFindingPegaso::fPrevXi, RootFindingBase::fX, RootFindingPegaso::prevXi, RootFindingPegaso::rootsObj, and RootFindingBase::x.
static void resetError (RootFindingPegasoT * pegasoObj) [static, private]
Definition at line 159 of file RootFindingPegaso.c.
References RootFindingPegaso::errorCode, RootFindingPegaso::PEGASO_ERROR_FOUND, RootFindingPegaso::PEGASO_NO_ERROR, RootFindingPegaso::PEGASO_NOT_INIT, and RootFindingPegaso::state.
RootFindingPegasoT* RootFindingPegasoCreate (RootFindingBaseT * rootsObj)
Cria um objeto do tipo struct RootFindingPegaso.
Parameters:
rootsObj Ponteiro para o objeto do tipo struct RootFindingBase
Returns:
Ponteiro para o objeto criado
Definition at line 47 of file RootFindingPegaso.c.
References RootFindingPegaso::maxIterations, PEGASO_DEFAULT_MAX_ITERATIONS, PEGASO_DEFAULT_TOLERANCE, RootFindingPegaso::PEGASO_NOT_INIT, resetError(), RootFindingPegaso::rootsObj, RootFindingPegaso::state, and RootFindingPegaso::tolerance.
void RootFindingPegasoDelete (RootFindingPegasoT * obj)
Apaga a instancia do objeto RootFindingPegaso.
Parameters:
obj Ponteiro para o obj RootFindingPegaso
Definition at line 81 of file RootFindingPegaso.c.
int RootFindingPegasoGetErrorCode (RootFindingPegasoT * pegasoObj)
Obtem o codigo de erro.
Definition at line 154 of file RootFindingPegaso.c.
References RootFindingPegaso::errorCode.
const char* RootFindingPegasoGetErrorMessage (RootFindingPegasoT * pegasoObj)
Obtem a mensagem de erro.
Definition at line 175 of file RootFindingPegaso.c.
References RootFindingPegaso::errorCode, MSG_PEGASO_NO_ERROR, MSG_PEGASO_X_ISINF_OR_ISNAN_ERROR, MSG_ROOTS_UNKNOW_ERROR, RootFindingPegaso::PEGASO_NO_ERROR, and RootFindingPegaso::PEGASO_X_ISINF_OR_ISNAN_ERROR.
int RootFindingPegasoGetStateCode (RootFindingPegasoT * pegasoObj)
Obtem o codigo referente ao estado do objeto.
Definition at line 168 of file RootFindingPegaso.c.
References RootFindingPegaso::state.
const char* RootFindingPegasoGetStateMessage (RootFindingPegasoT * pegasoObj)
Obtem a mensagem referente ao estado do objeto.
Definition at line 188 of file RootFindingPegaso.c.
References RootFindingBase::e, RootFindingPegaso::maxIterations, msg, MSG_PEGASO_APPROXIMANTION_ROOT_FOUND, MSG_PEGASO_ERROR_FOUND, MSG_PEGASO_INITIALIZED, MSG_PEGASO_MAX_ITERATIONS_LIMIT_REACHED, MSG_PEGASO_NOT_INIT, MSG_ROOTS_UNKNOW_STATE, RootFindingPegaso::PEGASO_APPROXIMANTION_ROOT_FOUND, RootFindingPegaso::PEGASO_ERROR_FOUND, RootFindingPegaso::PEGASO_INITIALIZED, RootFindingPegaso::PEGASO_MAX_ITERATIONS_LIMIT_REACHED, RootFindingPegaso::PEGASO_NOT_INIT, RootFindingPegaso::rootsObj, RootFindingPegaso::state, RootFindingPegaso::tolerance, and RootFindingBase::x.
RootFindingBoolT RootFindingPegasoHasError (RootFindingPegasoT * pegasoObj)
Verifica se ha erros.
Returns:
TRUE caso haja erro
Definition at line 213 of file RootFindingPegaso.c.
References RootFindingPegaso::errorCode, and RootFindingPegaso::PEGASO_NO_ERROR.
RootFindingBoolT RootFindingPegasoInit (RootFindingPegasoT * pegasoObj)
Inicializa o objeto RootFindingPegaso.
Parameters:
pegasoObj Ponteiro para o objeto a ser inicializado
Returns:
TRUE em caso de sucesso
Definition at line 63 of file RootFindingPegaso.c.
References RootFindingBase::a, RootFindingBase::b, RootFindingBase::e, RootFindingPegaso::fPrevXi, RootFindingBase::fX, RootFindingPegaso::i, RootFindingPegaso::PEGASO_INITIALIZED, RootFindingPegaso::prevXi, resetError(), RootFindingBaseEval(), RootFindingPegaso::rootsObj, RootFindingPegaso::state, TRUE, and RootFindingBase::x.
RootFindingBoolT RootFindingPegasoPerformIteration (RootFindingPegasoT * pegasoObj)
Realiza a iteracao.
Parameters:
pegasoObj Ponteiro para o objeto
Returns:
TRUE caso haja mais iteracoes a serem realizadas
Definition at line 108 of file RootFindingPegaso.c.
References RootFindingBase::e, FALSE, RootFindingPegaso::fPrevXi, RootFindingBase::fX, getNextX(), RootFindingPegaso::i, isInfOrNan(), RootFindingPegaso::maxIterations, RootFindingPegaso::PEGASO_APPROXIMANTION_ROOT_FOUND, RootFindingPegaso::PEGASO_MAX_ITERATIONS_LIMIT_REACHED, RootFindingPegaso::PEGASO_X_ISINF_OR_ISNAN_ERROR, RootFindingPegaso::prevXi, RootFindingBaseEval(), RootFindingPegaso::rootsObj, setError(), RootFindingPegaso::state, RootFindingBase::state, RootFindingPegaso::tolerance, TRUE, and RootFindingBase::x.
static void setError (RootFindingPegasoT * pegasoObj, int errorCode) [static, private]
Set error code and change state to PEGASO_ERROR_FOUND.
Parameters:
pegasoObj Ponteiro para objeto RootFindingPegasoT
errorCode Codigo de erro
Definition at line 102 of file RootFindingPegaso.c.
References RootFindingPegaso::errorCode, RootFindingPegaso::PEGASO_ERROR_FOUND, and RootFindingPegaso::state.