RootFinding: Metodo de Newton-Rhapson
Metodo de Newton-Rhapson
Data Structures
struct RootFindingNewtonRhapson
Estrutura de dados para o Metodo de Newton-Rhapson.
Defines
#define NEWTON_DEFAULT_MAX_ITERATIONS 100
#define NEWTON_DEFAULT_TOLERANCE 1e-7
Typedefs
typedef struct
RootFindingNewtonRhapson RootFindingNewtonRhapsonT
Apelido para struct RootFindingNewtonRhapson.
Functions
RootFindingNewtonRhapsonT * RootFindingNewtonRhapsonCreate (RootFindingBaseT *rootsObj)
Cria um objeto do tipo struct RootFindingNewtonRhapson.
RootFindingBoolT RootFindingNewtonRhapsonInit (RootFindingNewtonRhapsonT *newtonObj)
Inicializa o objeto RootFindingNewtonRhapson.
void RootFindingNewtonRhapsonDelete (RootFindingNewtonRhapsonT *newtonObj)
Apaga o objeto RootFindingNewtonRhapson.
RootFindingBoolT RootFindingNewtonRhapsonPerformIteration (RootFindingNewtonRhapsonT *newtonObj)
Realiza a iteracao.
int RootFindingNewtonRhapsonGetErrorCode (RootFindingNewtonRhapsonT *newtonObj)
Obtem o codigo de erro.
int RootFindingNewtonRhapsonGetStateCode (RootFindingNewtonRhapsonT *newtonObj)
Obtem o codigo referente ao estado do objeto.
const char * RootFindingNewtonRhapsonGetErrorMessage (RootFindingNewtonRhapsonT *newtonObj)
Obtem a mensagem de erro.
const char * RootFindingNewtonRhapsonGetStateMessage (RootFindingNewtonRhapsonT *newtonObj)
Obtem a mensagem referente ao estado do objeto.
RootFindingBoolT RootFindingNewtonRhapsonHasError (RootFindingNewtonRhapsonT *newtonObj)
Verifica se ha erros.
static void setError (RootFindingNewtonRhapsonT *newtonObj, int errorCode)
Set error code and change state to NEWTON_ERROR_FOUND.
static void resetError (RootFindingNewtonRhapsonT *newtonObj)
static RootFindingDoubleT getNextX (RootFindingNewtonRhapsonT *newtonObj)
Obtem o valor para o proximo x.
Define Documentation
#define NEWTON_DEFAULT_MAX_ITERATIONS 100
Definition at line 38 of file RootFindingNewtonRhapson.h.
Referenced by RootFindingNewtonRhapsonCreate().
#define NEWTON_DEFAULT_TOLERANCE 1e-7
Definition at line 39 of file RootFindingNewtonRhapson.h.
Referenced by RootFindingNewtonRhapsonCreate().
Typedef Documentation
typedef struct RootFindingNewtonRhapson RootFindingNewtonRhapsonT
Apelido para struct RootFindingNewtonRhapson.
Definition at line 87 of file RootFindingNewtonRhapson.h.
Function Documentation
static RootFindingDoubleT getNextX (RootFindingNewtonRhapsonT * newtonObj) [static, private]
Obtem o valor para o proximo x.
Parameters:
newtonObj Ponteiro para objeto struct RootFindingNewtonRhapson
Returns:
Valor do proximo x
Definition at line 127 of file RootFindingNewtonRhapson.c.
References RootFindingBase::fX, RootFindingBaseDiffEval(), RootFindingNewtonRhapson::rootsObj, and RootFindingBase::x.
static void resetError (RootFindingNewtonRhapsonT * newtonObj) [static, private]
Definition at line 195 of file RootFindingNewtonRhapson.c.
References RootFindingNewtonRhapson::errorCode, and RootFindingNewtonRhapson::state.
RootFindingNewtonRhapsonT* RootFindingNewtonRhapsonCreate (RootFindingBaseT * rootsObj)
Cria um objeto do tipo struct RootFindingNewtonRhapson.
Parameters:
rootsObj Ponteiro para objeto do tipo struct RootFindingBase
Returns:
Ponteiro para o objeto criado
Definition at line 47 of file RootFindingNewtonRhapson.c.
References RootFindingNewtonRhapson::maxIterations, NEWTON_DEFAULT_MAX_ITERATIONS, NEWTON_DEFAULT_TOLERANCE, resetError(), RootFindingNewtonRhapson::rootsObj, RootFindingNewtonRhapson::state, and RootFindingNewtonRhapson::tolerance.
void RootFindingNewtonRhapsonDelete (RootFindingNewtonRhapsonT * newtonObj)
Apaga o objeto RootFindingNewtonRhapson.
Parameters:
newtonObj Ponteiro para o objeto
Definition at line 115 of file RootFindingNewtonRhapson.c.
int RootFindingNewtonRhapsonGetErrorCode (RootFindingNewtonRhapsonT * newtonObj)
Obtem o codigo de erro.
Definition at line 190 of file RootFindingNewtonRhapson.c.
References RootFindingNewtonRhapson::errorCode.
const char* RootFindingNewtonRhapsonGetErrorMessage (RootFindingNewtonRhapsonT * newtonObj)
Obtem a mensagem de erro.
Definition at line 211 of file RootFindingNewtonRhapson.c.
References RootFindingBase::a, RootFindingBase::b, RootFindingBase::e, RootFindingNewtonRhapson::errorCode, msg, MSG_NEWTON_2NDIFF_TEST_ERROR, MSG_NEWTON_2NDIFFA_2NDIFFB_SIGN_NOT_EQUALS_ERROR, MSG_NEWTON_NO_ERROR, MSG_NEWTON_X_ISINF_OR_ISNAN_ERROR, MSG_ROOTS_UNKNOW_ERROR, RootFindingNewtonRhapson::rootsObj, and RootFindingBase::x.
int RootFindingNewtonRhapsonGetStateCode (RootFindingNewtonRhapsonT * newtonObj)
Obtem o codigo referente ao estado do objeto.
Definition at line 204 of file RootFindingNewtonRhapson.c.
References RootFindingNewtonRhapson::state.
const char* RootFindingNewtonRhapsonGetStateMessage (RootFindingNewtonRhapsonT * newtonObj)
Obtem a mensagem referente ao estado do objeto.
Definition at line 235 of file RootFindingNewtonRhapson.c.
References RootFindingBase::e, RootFindingNewtonRhapson::maxIterations, msg, MSG_NEWTON_APPROXIMANTION_ROOT_FOUND, MSG_NEWTON_ERROR_FOUND, MSG_NEWTON_INITIALIZED, MSG_NEWTON_MAX_ITERATIONS_LIMIT_REACHED, MSG_NEWTON_NOT_INIT, MSG_ROOTS_UNKNOW_STATE, RootFindingNewtonRhapson::rootsObj, RootFindingNewtonRhapson::state, RootFindingNewtonRhapson::tolerance, and RootFindingBase::x.
RootFindingBoolT RootFindingNewtonRhapsonHasError (RootFindingNewtonRhapsonT * newtonObj)
Verifica se ha erros.
Returns:
TRUE caso haja erro
Definition at line 260 of file RootFindingNewtonRhapson.c.
References RootFindingNewtonRhapson::errorCode.
RootFindingBoolT RootFindingNewtonRhapsonInit (RootFindingNewtonRhapsonT * newtonObj)
Inicializa o objeto RootFindingNewtonRhapson.
Parameters:
newtonObj Ponteiro para o objeto a ser inicializado
Returns:
TRUE em caso de sucesso, FALSE caso contrario
Definition at line 65 of file RootFindingNewtonRhapson.c.
References RootFindingBase::a, RootFindingBase::b, RootFindingBase::e, FALSE, RootFindingBase::fX, RootFindingNewtonRhapson::i, infinity(), RootFindingBase2nDiffEval(), RootFindingBaseEval(), RootFindingNewtonRhapson::rootsObj, setError(), RootFindingNewtonRhapson::state, TRUE, and RootFindingBase::x.
RootFindingBoolT RootFindingNewtonRhapsonPerformIteration (RootFindingNewtonRhapsonT * newtonObj)
Realiza a iteracao.
Parameters:
newtonObj Ponteiro para o objeto
Returns:
TRUE caso haja mais iteracoes a serem realizadas
Definition at line 146 of file RootFindingNewtonRhapson.c.
References RootFindingBase::e, FALSE, RootFindingBase::fX, getNextX(), RootFindingNewtonRhapson::i, isInfOrNan(), RootFindingNewtonRhapson::maxIterations, RootFindingBaseEval(), RootFindingNewtonRhapson::rootsObj, setError(), RootFindingNewtonRhapson::state, RootFindingBase::state, RootFindingNewtonRhapson::tolerance, TRUE, and RootFindingBase::x.
static void setError (RootFindingNewtonRhapsonT * newtonObj, int errorCode) [static, private]
Set error code and change state to NEWTON_ERROR_FOUND.
Parameters:
newtonObj Ponteiro para objeto RootFindingNewtonRhapson
errorCode Codigo de erro
Definition at line 140 of file RootFindingNewtonRhapson.c.
References RootFindingNewtonRhapson::errorCode, and RootFindingNewtonRhapson::state.