RootFinding: Metodo da Bissecao
Metodo da Bissecao
Data Structures
struct RootFindingBissecao
Estrutura de dados para o Metodo da Bissecao.
Defines
#define BISSECAO_DEFAULT_MAX_ITERATIONS 100
#define BISSECAO_DEFAULT_TOLERANCE 1e-7
Typedefs
typedef struct RootFindingBissecao RootFindingBissecaoT
Apelido para struct RootFindingBissecao.
Functions
RootFindingBissecaoT * RootFindingBissecaoCreate (RootFindingBaseT *rootsObj)
Cria um objeto do tipo struct RootFindingBissecao.
RootFindingBoolT RootFindingBissecaoInit (RootFindingBissecaoT *bissecaoObj)
Inicializa o objeto RootFindingBissecao.
void RootFindingBissecaoDelete (RootFindingBissecaoT *obj)
Apaga a instancia do objeto RootFindingBissecao.
RootFindingBoolT RootFindingBissecaoPerformIteration (RootFindingBissecaoT *bissecaoObj)
Realiza a iteracao.
void RootFindingBissecaoFindNewRange (RootFindingBaseT *rootsObj)
Encontra um novo intervalo [A, B] e os altera no objeto RootFindingBaseT baseado nos [A, B] e x existentes. Utilizado em RootFindingBissecaoPerformIteration porem principalmente util para alterar o intervalo quando intercambiando entre metodos diferentes.
int RootFindingBissecaoGetErrorCode (RootFindingBissecaoT *bissecaoObj)
Obtem o codigo de erro.
int RootFindingBissecaoGetStateCode (RootFindingBissecaoT *bissecaoObj)
Obtem o codigo referente ao estado do objeto.
const char * RootFindingBissecaoGetErrorMessage (RootFindingBissecaoT *bissecaoObj)
Obtem a mensagem de erro.
const char * RootFindingBissecaoGetStateMessage (RootFindingBissecaoT *bissecaoObj)
Obtem a mensagem referente ao estado do objeto.
RootFindingBoolT RootFindingBissecaoHasError (RootFindingBissecaoT *bissecaoObj)
Verifica se ha erros.
static void setError (RootFindingBissecaoT *bissecaoObj, int errorCode)
Set error code and change state to BISSECAO_ERROR_FOUND.
static void resetError (RootFindingBissecaoT *bissecaoObj)
static RootFindingDoubleT computeX (RootFindingBissecaoT *bissecaoObj)
Calcula o X baseado no intervalo [a, b].
Define Documentation
#define BISSECAO_DEFAULT_MAX_ITERATIONS 100
Definition at line 34 of file RootFindingBissecao.h.
Referenced by RootFindingBissecaoCreate().
#define BISSECAO_DEFAULT_TOLERANCE 1e-7
Definition at line 35 of file RootFindingBissecao.h.
Referenced by RootFindingBissecaoCreate().
Typedef Documentation
typedef struct RootFindingBissecao RootFindingBissecaoT
Apelido para struct RootFindingBissecao.
Definition at line 77 of file RootFindingBissecao.h.
Function Documentation
static RootFindingDoubleT computeX (RootFindingBissecaoT * bissecaoObj) [static, private]
Calcula o X baseado no intervalo [a, b].
Parameters:
bissecaoObj Ponteiro para o objeto RootFindingBissecao
Returns:
O X calculado
Definition at line 70 of file RootFindingBissecao.c.
References RootFindingBase::a, RootFindingBase::b, and RootFindingBissecao::rootsObj.
Referenced by RootFindingBissecaoInit(), and RootFindingBissecaoPerformIteration().
static void resetError (RootFindingBissecaoT * bissecaoObj) [static, private]
Definition at line 164 of file RootFindingBissecao.c.
References RootFindingBissecao::errorCode, and RootFindingBissecao::state.
Referenced by RootFindingBissecaoCreate(), RootFindingBissecaoInit(), RootFindingCordasCreate(), RootFindingCordasInit(), RootFindingNewtonRhapsonCreate(), RootFindingPegasoCreate(), and RootFindingPegasoInit().
RootFindingBissecaoT* RootFindingBissecaoCreate (RootFindingBaseT * rootsObj)
Cria um objeto do tipo struct RootFindingBissecao.
Parameters:
rootsObj Ponteiro para o objeto do tipo struct RootFindingBase
Returns:
Ponteiro para o objeto criado
Definition at line 47 of file RootFindingBissecao.c.
References BISSECAO_DEFAULT_MAX_ITERATIONS, BISSECAO_DEFAULT_TOLERANCE, RootFindingBissecao::maxIterations, resetError(), RootFindingBissecao::rootsObj, RootFindingBissecao::state, and RootFindingBissecao::tolerance.
void RootFindingBissecaoDelete (RootFindingBissecaoT * obj)
Apaga a instancia do objeto RootFindingBissecao.
Parameters:
obj Ponteiro para o obj RootFindingBissecao
Definition at line 90 of file RootFindingBissecao.c.
void RootFindingBissecaoFindNewRange (RootFindingBaseT * rootsObj)
Encontra um novo intervalo [A, B] e os altera no objeto RootFindingBaseT baseado nos [A, B] e x existentes. Utilizado em RootFindingBissecaoPerformIteration porem principalmente util para alterar o intervalo quando intercambiando entre metodos diferentes.
Parameters:
rootsObj Ponteiro para o objeto RootFindingBase
Definition at line 139 of file RootFindingBissecao.c.
References RootFindingBase::a, RootFindingBase::b, RootFindingBase::fX, RootFindingBaseEval(), and RootFindingBase::x.
Referenced by RootFindingBissecaoPerformIteration().
int RootFindingBissecaoGetErrorCode (RootFindingBissecaoT * bissecaoObj)
Obtem o codigo de erro.
Definition at line 159 of file RootFindingBissecao.c.
References RootFindingBissecao::errorCode.
const char* RootFindingBissecaoGetErrorMessage (RootFindingBissecaoT * bissecaoObj)
Obtem a mensagem de erro.
Definition at line 180 of file RootFindingBissecao.c.
References RootFindingBissecao::errorCode, MSG_BISSECAO_NO_ERROR, MSG_BISSECAO_X_ISINF_OR_ISNAN_ERROR, and MSG_ROOTS_UNKNOW_ERROR.
int RootFindingBissecaoGetStateCode (RootFindingBissecaoT * bissecaoObj)
Obtem o codigo referente ao estado do objeto.
Definition at line 173 of file RootFindingBissecao.c.
References RootFindingBissecao::state.
const char* RootFindingBissecaoGetStateMessage (RootFindingBissecaoT * bissecaoObj)
Obtem a mensagem referente ao estado do objeto.
Definition at line 194 of file RootFindingBissecao.c.
References RootFindingBase::e, RootFindingBissecao::maxIterations, msg, MSG_BISSECAO_APPROXIMANTION_ROOT_FOUND, MSG_BISSECAO_ERROR_FOUND, MSG_BISSECAO_INITIALIZED, MSG_BISSECAO_MAX_ITERATIONS_LIMIT_REACHED, MSG_BISSECAO_NOT_INIT, MSG_ROOTS_UNKNOW_STATE, RootFindingBissecao::rootsObj, RootFindingBissecao::state, RootFindingBissecao::tolerance, and RootFindingBase::x.
RootFindingBoolT RootFindingBissecaoHasError (RootFindingBissecaoT * bissecaoObj)
Verifica se ha erros.
Returns:
TRUE caso haja erro
Definition at line 220 of file RootFindingBissecao.c.
References RootFindingBissecao::errorCode.
RootFindingBoolT RootFindingBissecaoInit (RootFindingBissecaoT * bissecaoObj)
Inicializa o objeto RootFindingBissecao.
Parameters:
bissecaoObj Ponteiro para o objeto a ser inicializado
Returns:
TRUE em caso de sucesso
Definition at line 77 of file RootFindingBissecao.c.
References computeX(), RootFindingBase::e, RootFindingBase::fX, RootFindingBissecao::i, infinity(), resetError(), RootFindingBaseEval(), RootFindingBissecao::rootsObj, RootFindingBissecao::state, TRUE, and RootFindingBase::x.
RootFindingBoolT RootFindingBissecaoPerformIteration (RootFindingBissecaoT * bissecaoObj)
Realiza a iteracao.
Parameters:
bissecaoObj Ponteiro para o objeto
Returns:
TRUE caso haja mais iteracoes a serem realizadas
Definition at line 95 of file RootFindingBissecao.c.
References computeX(), RootFindingBase::e, FALSE, RootFindingBase::fX, RootFindingBissecao::i, isInfOrNan(), RootFindingBissecao::maxIterations, RootFindingBaseEval(), RootFindingBissecaoFindNewRange(), RootFindingBissecao::rootsObj, setError(), RootFindingBissecao::state, RootFindingBase::state, RootFindingBissecao::tolerance, TRUE, and RootFindingBase::x.
static void setError (RootFindingBissecaoT * bissecaoObj, int errorCode) [static, private]
Set error code and change state to BISSECAO_ERROR_FOUND.
Parameters:
bissecaoObj Ponteiro para objeto RootFindingBissecaoT
errorCode Codigo de erro
Definition at line 153 of file RootFindingBissecao.c.
References RootFindingBissecao::errorCode, and RootFindingBissecao::state.
Referenced by RootFindingBissecaoPerformIteration(), RootFindingCordasInit(), RootFindingCordasPerformIteration(), RootFindingNewtonRhapsonInit(), RootFindingNewtonRhapsonPerformIteration(), and RootFindingPegasoPerformIteration().