RootFinding: Metodo das Cordas
Metodo das Cordas
Data Structures
struct RootFindingCordas
Estrutura de dados para o Metodo das Cordas.
Defines
#define CORDAS_DEFAULT_MAX_ITERATIONS 100
#define CORDAS_DEFAULT_TOLERANCE 1e-7
Typedefs
typedef struct RootFindingCordas RootFindingCordasT
Apelido para struct RootFindingCordas.
Functions
RootFindingCordasT * RootFindingCordasCreate (RootFindingBaseT *rootsObj)
Cria um objeto do tipo struct RootFindingCordas.
RootFindingBoolT RootFindingCordasInit (RootFindingCordasT *cordasObj)
Inicializa o objeto RootFindingCordas.
void RootFindingCordasDelete (RootFindingCordasT *obj)
Apaga a instancia do objeto RootFindingCordas.
RootFindingBoolT RootFindingCordasPerformIteration (RootFindingCordasT *cordasObj)
Realiza a iteracao.
int RootFindingCordasGetErrorCode (RootFindingCordasT *cordasObj)
Obtem o codigo de erro.
int RootFindingCordasGetStateCode (RootFindingCordasT *cordasObj)
Obtem o codigo referente ao estado do objeto.
const char * RootFindingCordasGetErrorMessage (RootFindingCordasT *cordasObj)
Obtem a mensagem de erro.
const char * RootFindingCordasGetStateMessage (RootFindingCordasT *cordasObj)
Obtem a mensagem referente ao estado do objeto.
RootFindingBoolT RootFindingCordasHasError (RootFindingCordasT *cordasObj)
Verifica se ha erros.
static void setError (RootFindingCordasT *cordasObj, int errorCode)
Set error code and change state to CORDAS_ERROR_FOUND.
static void resetError (RootFindingCordasT *cordasObj)
static RootFindingDoubleT getNextX (RootFindingCordasT *cordasObj)
Obtem o valor para o proximo x.
Define Documentation
#define CORDAS_DEFAULT_MAX_ITERATIONS 100
Definition at line 38 of file RootFindingCordas.h.
Referenced by RootFindingCordasCreate().
#define CORDAS_DEFAULT_TOLERANCE 1e-7
Definition at line 39 of file RootFindingCordas.h.
Referenced by RootFindingCordasCreate().
Typedef Documentation
typedef struct RootFindingCordas RootFindingCordasT
Apelido para struct RootFindingCordas.
Definition at line 84 of file RootFindingCordas.h.
Function Documentation
static RootFindingDoubleT getNextX (RootFindingCordasT * cordasObj) [static, private]
Obtem o valor para o proximo x.
Parameters:
cordasObj Ponteiro para objeto struct RootFindingCordas
Returns:
Valor do proximo x
Definition at line 118 of file RootFindingCordas.c.
References RootFindingCordas::c, RootFindingCordas::fC, RootFindingBase::fX, RootFindingCordas::rootsObj, and RootFindingBase::x.
Referenced by RootFindingCordasPerformIteration(), RootFindingNewtonRhapsonPerformIteration(), and RootFindingPegasoPerformIteration().
static void resetError (RootFindingCordasT * cordasObj) [static, private]
Definition at line 186 of file RootFindingCordas.c.
References RootFindingCordas::errorCode, and RootFindingCordas::state.
RootFindingCordasT* RootFindingCordasCreate (RootFindingBaseT * rootsObj)
Cria um objeto do tipo struct RootFindingCordas.
Parameters:
rootsObj Ponteiro para o objeto do tipo struct RootFindingBase
Returns:
Ponteiro para o objeto criado
Definition at line 48 of file RootFindingCordas.c.
References CORDAS_DEFAULT_MAX_ITERATIONS, CORDAS_DEFAULT_TOLERANCE, RootFindingCordas::maxIterations, resetError(), RootFindingCordas::rootsObj, RootFindingCordas::state, and RootFindingCordas::tolerance.
void RootFindingCordasDelete (RootFindingCordasT * obj)
Apaga a instancia do objeto RootFindingCordas.
Parameters:
obj Ponteiro para o obj RootFindingCordas
Definition at line 127 of file RootFindingCordas.c.
int RootFindingCordasGetErrorCode (RootFindingCordasT * cordasObj)
Obtem o codigo de erro.
Definition at line 181 of file RootFindingCordas.c.
References RootFindingCordas::errorCode.
const char* RootFindingCordasGetErrorMessage (RootFindingCordasT * cordasObj)
Obtem a mensagem de erro.
Definition at line 202 of file RootFindingCordas.c.
References RootFindingBase::a, RootFindingBase::b, RootFindingCordas::errorCode, msg, MSG_CORDAS_2NDIFF_TEST_ERROR, MSG_CORDAS_NO_ERROR, MSG_CORDAS_X_ISINF_OR_ISNAN_ERROR, MSG_ROOTS_UNKNOW_ERROR, and RootFindingCordas::rootsObj.
int RootFindingCordasGetStateCode (RootFindingCordasT * cordasObj)
Obtem o codigo referente ao estado do objeto.
Definition at line 195 of file RootFindingCordas.c.
References RootFindingCordas::state.
const char* RootFindingCordasGetStateMessage (RootFindingCordasT * cordasObj)
Obtem a mensagem referente ao estado do objeto.
Definition at line 219 of file RootFindingCordas.c.
References RootFindingBase::e, RootFindingCordas::maxIterations, msg, MSG_CORDAS_APPROXIMANTION_ROOT_FOUND, MSG_CORDAS_ERROR_FOUND, MSG_CORDAS_INITIALIZED, MSG_CORDAS_MAX_ITERATIONS_LIMIT_REACHED, MSG_CORDAS_NOT_INIT, MSG_ROOTS_UNKNOW_STATE, RootFindingCordas::rootsObj, RootFindingCordas::state, RootFindingCordas::tolerance, and RootFindingBase::x.
RootFindingBoolT RootFindingCordasHasError (RootFindingCordasT * cordasObj)
Verifica se ha erros.
Returns:
TRUE caso haja erro
Definition at line 244 of file RootFindingCordas.c.
References RootFindingCordas::errorCode.
RootFindingBoolT RootFindingCordasInit (RootFindingCordasT * cordasObj)
Inicializa o objeto RootFindingCordas.
Parameters:
cordasObj Ponteiro para o objeto a ser inicializado
Returns:
TRUE em caso de sucesso
Definition at line 64 of file RootFindingCordas.c.
References RootFindingBase::a, RootFindingBase::b, RootFindingCordas::c, RootFindingBase::e, FALSE, RootFindingCordas::fC, RootFindingBase::fX, RootFindingCordas::i, infinity(), resetError(), RootFindingBase2nDiffEval(), RootFindingBaseEval(), RootFindingCordas::rootsObj, setError(), RootFindingCordas::state, TRUE, and RootFindingBase::x.
RootFindingBoolT RootFindingCordasPerformIteration (RootFindingCordasT * cordasObj)
Realiza a iteracao.
Parameters:
cordasObj Ponteiro para o objeto
Returns:
TRUE caso haja mais iteracoes a serem realizadas
Definition at line 138 of file RootFindingCordas.c.
References RootFindingBase::e, FALSE, RootFindingBase::fX, getNextX(), RootFindingCordas::i, isInfOrNan(), RootFindingCordas::maxIterations, RootFindingBaseEval(), RootFindingCordas::rootsObj, setError(), RootFindingCordas::state, RootFindingBase::state, RootFindingCordas::tolerance, TRUE, and RootFindingBase::x.
static void setError (RootFindingCordasT * cordasObj, int errorCode) [static, private]
Set error code and change state to CORDAS_ERROR_FOUND.
Parameters:
cordasObj Ponteiro para objeto RootFindingCordasT
errorCode Codigo de erro
Definition at line 132 of file RootFindingCordas.c.
References RootFindingCordas::errorCode, and RootFindingCordas::state.