RootFinding: include/RootFindingCommon.h File Reference
include/RootFindingCommon.h File Reference
/root-finding/include/RootFindingCommon.h
#include <muParserDLL.h>
Defines
#define TRUE 1
#define FALSE 0
Typedefs
typedef double RootFindingDoubleT
typedef int RootFindingBoolT
Functions
RootFindingBoolT getAxisVarPtr (muParserHandle_t mupObj, const char *axis, RootFindingDoubleT **varPtr)
Obtem o endereco para a variavel do eixo onde deve-se.
RootFindingDoubleT Mup2ndDiff (muParserHandle_t mupObj, RootFindingDoubleT *varPtr)
Aproximacao da segunda diferencial no ponto utilizando "Finite difference".
RootFindingDoubleT MupDiff (muParserHandle_t mupObj, RootFindingDoubleT *varPtr)
Aproximacao da diferencial no ponto utilizando "regard to a variable" O codigo foi adaptado para C c/ base no metodo Diff da classe muParser (C++), infelizmente a API para C do muParser nao disbonibiliza o metodo Diff.
RootFindingDoubleT infinity ()
Obtem o valor infinito.
RootFindingBoolT isInfOrNan (RootFindingDoubleT num)
Verifica se um dado numero RootFindingDoubleT eh infinito ou "Not a Number".
Detailed Description
/root-finding/include/RootFindingCommon.h
Date:
25/03/2010
Author:
Matheus Neder <matheusneder@gmail.com>
Definition in file RootFindingCommon.h.
Define Documentation
#define FALSE 0
Definition at line 39 of file RootFindingCommon.h.
Referenced by getAxisVarPtr(), RootFindingBaseSetRange(), RootFindingBissecaoPerformIteration(), RootFindingCordasInit(), RootFindingCordasPerformIteration(), RootFindingNewtonRhapsonInit(), RootFindingNewtonRhapsonPerformIteration(), and RootFindingPegasoPerformIteration().
#define TRUE 1
Definition at line 36 of file RootFindingCommon.h.
Referenced by getAxisVarPtr(), RootFindingBaseSetRange(), RootFindingBissecaoInit(), RootFindingBissecaoPerformIteration(), RootFindingCordasInit(), RootFindingCordasPerformIteration(), RootFindingNewtonRhapsonInit(), RootFindingNewtonRhapsonPerformIteration(), RootFindingPegasoInit(), and RootFindingPegasoPerformIteration().
Typedef Documentation
typedef int RootFindingBoolT
Definition at line 33 of file RootFindingCommon.h.
typedef double RootFindingDoubleT
Definition at line 31 of file RootFindingCommon.h.
Function Documentation
RootFindingBoolT getAxisVarPtr (muParserHandle_t mupObj, const char * axis, RootFindingDoubleT ** varPtr)
Obtem o endereco para a variavel do eixo onde deve-se.
Parameters:
mupObj Ponteiro para objeto muParser contendo a expressao
axis Eixo em qual a raiz deve ser procurada
[out] varPtr Ponteiro para onde o endereco deve ser atribuido
Returns:
TRUE em caso de sucesso FALSE em caso de falha
Definition at line 30 of file RootFindingCommon.c.
References FALSE, RootFindingPegaso::i, and TRUE.
RootFindingDoubleT infinity ()
Obtem o valor infinito.
Returns:
inf
Definition at line 55 of file RootFindingCommon.c.
Referenced by RootFindingBaseReset(), RootFindingBissecaoInit(), RootFindingCordasInit(), and RootFindingNewtonRhapsonInit().
RootFindingBoolT isInfOrNan (RootFindingDoubleT num)
Verifica se um dado numero RootFindingDoubleT eh infinito ou "Not a Number".
Parameters:
num Numero a verificado
Returns:
TRUE se isinf(num) ou isnan(num)
Definition at line 97 of file RootFindingCommon.c.
Referenced by RootFindingBissecaoPerformIteration(), RootFindingCordasPerformIteration(), RootFindingNewtonRhapsonPerformIteration(), and RootFindingPegasoPerformIteration().
RootFindingDoubleT Mup2ndDiff (muParserHandle_t mupObj, RootFindingDoubleT * varPtr)
Aproximacao da segunda diferencial no ponto utilizando "Finite difference".
Parameters:
mupObj Objeto muParser (ponteiro)
varPtr Ponteiro para a variavel relacionada a expressao no objeto muParser referente a qual variavel deve ser diferenciado
Returns:
Valor da segunda diferencial no ponto
Definition at line 61 of file RootFindingCommon.c.
Referenced by RootFindingBase2nDiffEval().
RootFindingDoubleT MupDiff (muParserHandle_t mupObj, RootFindingDoubleT * varPtr)
Aproximacao da diferencial no ponto utilizando "regard to a variable" O codigo foi adaptado para C c/ base no metodo Diff da classe muParser (C++), infelizmente a API para C do muParser nao disbonibiliza o metodo Diff.
Parameters:
mupObj Objeto muParser (ponteiro)
varPtr Ponteiro para a variavel relacionada a expressao no objeto muParser referente a qual variavel deve ser diferenciado
Returns:
Valor da diferencial no ponto
Definition at line 77 of file RootFindingCommon.c.
Referenced by RootFindingBaseDiffEval().